// micro-front-app/packages/micro-app-vue/src/pages/list/index.vue
<template>
  <section>
    <a-card title="Vue 子应用列表页">
      列表页
    </a-card>
  </section>
</template>

<script>
import fetch from "isomorphic-fetch";

export default {
  name: "List",

  data() {
    return {
      data: [],
      pageInfo: {
        onChange: page => this.fetchUsers(page, 10)
      },
    }
  },
  
  methods: {
    async fetchUsers () {
      return fetch("/user", {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        }
      }).then((res) => res.json());
    }
  },

  created() {
    this.fetchUsers(1, 10);
  }
}
</script>

// micro-front-app/packages/micro-app-react/src/pages/list/index.jsx
import React, { useState, useEffect } from "react";
import { Card, Table, Avatar } from "antd";
import fetch from "isomorphic-fetch";

const fetchUsers = () => {
  return fetch("/user", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    }
  }).then((res) => res.json());
};

const { Column } = Table;
const List = () => {
  // 设置列表信息
  const [data, setData] = useState([]);
  // 设置页码信息
  const [page, setPage] = useState(1);
  const [pageInfo, setPageInfo] = useState();

  useEffect(() => {
    console.log({ page });
    (async () => {
      const result = await fetchUsers();
      
    })();
  }, [page]);

  return (
    <Card title="React 子应用列表页">
      列表页
    </Card>
  );
};

export default List;
