// vue-vite-admin/src/pages/result/404.vue
<template>
  <result title="404 Not Found" tip="抱歉，您访问的页面不存在" type="404">
    <el-button type="primary" @click="() => $router.push('/')">返回首页</el-button>
  </result>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Result404",
});
</script>

// react-vite-admin-antd-redux/src/pages/result/404/index.tsx
import { memo } from "react";
import { Button, Result } from "antd";
import { useRoute } from "@/hooks";

const NotFound = () => {
  const { history } = useRoute();
  return (
    <Result
      status="404"
      title="404 Not Found"
      subTitle="抱歉，您访问的页面不存在."
      extra={
        <Button
          type="primary"
          onClick={() => {
            history.replace("/");
          }}
        >
          返回上一页
        </Button>
      }
    />
  );
};
export default memo(NotFound);
