// react-vite-admin-antd-redux/src/pages/result/404/index.tsx
import { memo } from "react";
import { Button, Result } from "antd";
import { useRoute } from "@/hooks";

const NotFound = () => {
  const { history } = useRoute();
  return (
    <Result
      status="404"
      title="404 Not Found"
      subTitle="抱歉，您访问的页面不存在."
      extra={
        <Button
          type="primary"
          onClick={() => {
            history.replace("/");
          }}
        >
          返回上一页
        </Button>
      }
    />
  );
};
export default memo(NotFound);

// vue-vite-admin-simple/src/pages/result/404.vue
<template>
  <result title="404 Not Found" tip="抱歉，您访问的页面不存在" type="404">
    <el-button type="primary" @click="() => $router.go(-1)"
      >返回上一页 ({{ second }}s)</el-button
    >
  </result>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import { useRouter } from "vue-router";
import { useIntervalFn } from "@vueuse/core";

export default defineComponent({
  name: "Result404",
  setup() {
    const second = ref(5);
    const router = useRouter();

    useIntervalFn(() => {
      if (second.value === 1) {
        router.go(-1);
      } else {
        second.value--;
      }
    }, 1000);

    return {
      second,
    };
  },
});
</script>
