// vue-vite-admin/src/pages/demo/components/Counter.tsx
import { defineComponent } from "vue";
import { useStore } from "@/context/CountProvider";
export default defineComponent({
  name: "Counter",

  setup() {
    const { state, dispatch }: any = useStore();

    console.log("store:", state);
    const increment = () => {
      dispatch("increment");
    };
    const decrement = () => {
      dispatch("decrement");
    };


    return () => {
      return (
        <div class="md:container md:mx-auto">
          <p>
            <button class="px-4 py-1 rounded inline-block bg-teal-600 text-white cursor-pointer hover:bg-teal-700 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50"
             onClick={increment}>+</button>
            {state.count}
            <button class="px-4 py-1 rounded inline-block bg-teal-600 text-white cursor-pointer hover:bg-teal-700 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50"
             onClick={decrement}>-</button>
          </p>
        </div>
      );
    };
  },
});

// react-zustand-context/src/pages/demos/components/Counter.tsx
import { useStore } from 'zustand';
import { store } from '@/store';

const Counter = () => {
  const [count, decrement, increment, resetCount] = useStore(store, (s) => [
    s.count,
    s.decrement,
    s.increment,
    s.resetCount,
  ]);

  const { getState, setState, subscribe, destroy } = store;
  
  return (
    <div>
      <h2>zustand state</h2>
      <span>计数: {count}</span>
      <button className="btn" type="button" onClick={increment}>
        +
      </button>
      <button className="btn" type="button" onClick={decrement}>
        -
      </button>

      <button className="btn" type="button" onClick={resetCount}>
        重置
      </button>
      <button
        onClick={() => {
          setState({ count: 10 });
        }}
      >
        setState()
      </button>
      <button
        onClick={() => {
          console.log(getState());
        }}
      >
        getState()
      </button>
    </div>
  );
};

export default Counter;
