// react-template/src/pages/index.tsx
import { useAtomValue } from 'jotai'
import { createFileRoute } from '@tanstack/react-router'
import { counterAtom } from '@/atoms/counter'
import { fetchGithubRepo } from '@/api'

export const Route = createFileRoute('/')({
  component: Home,
})
function Content() {
  const count = useAtomValue(counterAtom)
  return (
    <div className="home">
      <div className="i-carbon-campsite inline-block text-4xl" />
      <p>
        <a rel="noreferrer" href="https://github.com/yang1206/react-template" target="_blank">
          Vitesse Lite for React
        </a>
      </p>
      <p>
        <em className="text-sm opacity-75">Opinionated Vite Starter Template</em>
      </p>
      <div className="py-4" />
      <p className="font-mono font-semibold">{count}</p>
    </div>
  )
}
function Home() {
  const { data, isLoading } = fetchGithubRepo({
    variables: { repo: 'yang1206/react-template' },
  })
  if (isLoading)
    return <div>Loading...</div>

  return (
    <>
      <Content />
      <a className="block" href={data?.html_url}>{data?.full_name}</a>
    </>
  )
}

// vue-template/src/pages/index.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'
import { fetchGithubRepo } from '@/api'
import { useCounterStore } from '@/store'

const { count } = useCounterStore()
const { data, isLoading } = useQuery({
  ...fetchGithubRepo('yang1206/vue-template'),
})
</script>

<template>
  <div class="home">
    <div class="i-carbon-campsite inline-block text-4xl" />
    <p>
      <a rel="noreferrer" href="https://github.com/yang1206/vue-template" target="_blank">
        a Vue3，Vite template
      </a>
    </p>
    <p>
      <em class="text-sm op75">Opinionated Vite Starter Template</em>
    </p>

    <div class="py-4" />
    <p class="font-semibold">
      {{ count }}
    </p>
  </div>
  <p v-if="isLoading">
    Loading...
  </p>
  <a v-else className="block" :href="data?.html_url">{{ data?.full_name }}</a>
</template>
